### ISSUE TITLE
Geoparquet ?

### ISSUE THREAD

**Issue by ymoisan** [Ylannl/CityBuf#1]
Considering geoparquet already supports 3D and more importantly considering parquet is a very performant file format already used by big "cloud" libraries (like Delta Lake or Iceberg), would it not make sense to store CityObjects in parquet ?

**Comment by Ylannl** [comment]
That depends on your usecase. The goal with CityBuf is to have a very fast and memory-efficient format that allows for streaming reading/writing. Furthermore, CityBuf is aimed to be fully compatible with CityJSON which is somewhat difficult to achieve with a column based format like parquet, eg. the ability to store attributes per face in a 3D solid. Also geoparquet does not support all the geometry types that CityJSON does.

**Comment by ymoisan** [comment]
I'll admit to not being very cognizant of 3D peculiarities.  Parquet is likely to store raster data soon (in the form of [Rasquet](https://carto.com/blog/sdsc2024-climate-change-geo-ai-carto-ai-agents)) so I was thinking maybe there is a way to store 3D in parquet too.

**Comment by ymoisan** [comment]
> Parquet is likely to store raster data soon (in the form of [Rasquet](https://carto.com/blog/sdsc2024-climate-change-geo-ai-carto-ai-agents))

Now official : https://github.com/CartoDB/raquet
